import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen bg-[#ffffff]">
          <div className="h-24">
            <Navbar/>
          </div>
          <div className="h-[100vh-96px]">
            {children}
          </div>
          <div className="h-96">
            <Footer/>
          </div>
        </div>
        </body>
    </html>
  );
}
